spring.application.name=possystem
# 1. The Connection Keys
spring.datasource.url=jdbc:mysql://localhost:3306/pos_db
spring.datasource.username=root
spring.datasource.password=your_password

# 2. The JPA / Hibernate Magic
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true